var searchData=
[
  ['u16streampos_0',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string_1',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u16string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u16string']]],
  ['u16string_5fview_2',['u16string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u16string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u16string_view']]],
  ['u32streampos_3',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string_4',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::u32string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::u32string']]],
  ['u32string_5fview_5',['u32string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::u32string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::u32string_view']]],
  ['uint16_5ft_6',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft_7',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft_8',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft_9',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft_10',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft_11',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft_12',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft_13',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft_14',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft_15',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft_16',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft_17',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft_18',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft_19',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['unary_5ffunction_20',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate_21',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['underflow_5ferror_22',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype_23',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['underlying_5ftype_5ft_24',['underlying_type_t',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpected_5fhandler_25',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['uniform_5fint_5fdistribution_26',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution_27',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5flock_28',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr_29',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unordered_5fmap_30',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::pmr::unordered_map'],['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std::unordered_map&lt; K, T &gt;']]],
  ['unordered_5fmultimap_31',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::pmr::unordered_multimap'],['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std::unordered_multimap&lt; K, T &gt;']]],
  ['unordered_5fmultiset_32',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::pmr::unordered_multiset'],['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std::unordered_multiset&lt; K &gt;']]],
  ['unordered_5fset_33',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::pmr::unordered_set'],['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std::unordered_set&lt; K &gt;']]],
  ['unsynchronized_5fpool_5fresource_34',['unsynchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/unsynchronized_pool_resource.html',1,'std::experimental::pmr::unsynchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/unsynchronized_pool_resource.html',1,'std::pmr::unsynchronized_pool_resource']]],
  ['uses_5fallocator_35',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]]
];
